stages:
  - release

release:
  extends:
    - .fargate-golang
  stage: release
  script:
    - echo $GPG_PRIVATE_KEY | gpg --import
    - GPG_FINGERPRINT=$(gpg --list-secret-keys --keyid-format short knowbe4-tflint | awk 'FNR == 2 {print$1}')
    - go install github.com/goreleaser/goreleaser@latest
    - goreleaser



include:
  - project: docker/gitlab-fargate-runners
    file: .gitlab/task_defintions.yml
