stages:
  - build
  - upload
  - release

.base-matrix:
  parallel:
    matrix:
      - GOOS: ["darwin", "linux"]
        GOARCH: ["arm64", "amd64"]

build:
  extends:
    - .fargate-golang
    - .base-matrix
  stage: build
  script:
    - apk add --no-cache zip
    - go build -o build/tflint-ruleset-kb4_${GOOS}_${GOARCH}
    - |
      zip -j tflint-ruleset-kb4_${GOOS}_${GOARCH}.zip build/tflint-ruleset-kb4_${GOOS}_${GOARCH}

  artifacts:
    paths:
      - tflint-ruleset-kb4_${GOOS}_${GOARCH}.zip

upload:
  extends:
    - .fargate-golang
    - .base-matrix
  stage: upload
  script:
    - apk add --no-cache curl
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file tflint-ruleset-kb4_${GOOS}_${GOARCH}.zip "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/tflint-ruleset-kb4_${GOOS}_${GOARCH}/$(cat VERSION)/tflint-ruleset-kb4_${GOOS}_${GOARCH}.zip"
  dependencies:
    - build


release:
  extends:
    - .fargate-golang
  stage: release
  script:
    - apk add --no-cache curl
    - curl https://gitlab.com/api/v4/projects/16573099/packages/generic/release-cli/v0.11.0/release-cli-linux-amd64 --output release-cli && chmod +x release-cli
    - |
      ./release-cli create --name "Release $(cat VERSION)" --tag-name $(cat VERSION) \
        --assets-link "{\"name\":\"darwin_amd64\",\"url\":\"${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/tflint-ruleset-kb4/$(cat VERSION)/tflint-ruleset-kb4_darwin_amd64.zip\"}" \
        --assets-link "{\"name\":\"darwin_arm64\",\"url\":\"${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/tflint-ruleset-kb4/$(cat VERSION)/tflint-ruleset-kb4_darwin_arm64.zip\"}" \
        --assets-link "{\"name\":\"linux_amd64\",\"url\":\"${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/tflint-ruleset-kb4/$(cat VERSION)/tflint-ruleset-kb4_linux_amd64.zip\"}" \
        --assets-link "{\"name\":\"linux_arm64\",\"url\":\"${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/tflint-ruleset-kb4/$(cat VERSION)/tflint-ruleset-kb4_linux_arm64.zip\"}" \
  dependencies:
    - upload


include:
  - project: docker/gitlab-fargate-runners
    file: .gitlab/task_defintions.yml
